/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_aloyenz_t501_driver_virtual_VMouse */

#ifndef _Included_ru_aloyenz_t501_driver_virtual_VMouse
#define _Included_ru_aloyenz_t501_driver_virtual_VMouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_aloyenz_t501_driver_virtual_VMouse
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ru_aloyenz_t501_driver_virtual_VMouse_initialize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ru_aloyenz_t501_driver_virtual_VMouse
 * Method:    mouseEvent
 * Signature: (J[I[Z[I)I
 */
JNIEXPORT jint JNICALL Java_ru_aloyenz_t501_driver_virtual_VMouse_mouseEvent
  (JNIEnv *, jclass, jlong, jintArray, jbooleanArray, jintArray);

/*
 * Class:     ru_aloyenz_t501_driver_virtual_VMouse
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_aloyenz_t501_driver_virtual_VMouse_shutdown
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
