/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_aloyenz_t501_driver_VPen */

#ifndef _Included_ru_aloyenz_t501_driver_VPen
#define _Included_ru_aloyenz_t501_driver_VPen
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_aloyenz_t501_driver_VPen
 * Method:    initialize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ru_aloyenz_t501_driver_VPen_initialize
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ru_aloyenz_t501_driver_VPen
 * Method:    writePosition
 * Signature: (JIIIZII)I
 */
JNIEXPORT jint JNICALL Java_ru_aloyenz_t501_driver_VPen_writePosition
  (JNIEnv *, jclass, jlong, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     ru_aloyenz_t501_driver_VPen
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_aloyenz_t501_driver_VPen_shutdown
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
