/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_aloyenz_t501_driver_virtual_VKeyboard */

#ifndef _Included_ru_aloyenz_t501_driver_virtual_VKeyboard
#define _Included_ru_aloyenz_t501_driver_virtual_VKeyboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_aloyenz_t501_driver_virtual_VKeyboard
 * Method:    initialize
 * Signature: (Ljava/lang/String;[I)J
 */
JNIEXPORT jlong JNICALL Java_ru_aloyenz_t501_driver_virtual_VKeyboard_initialize
  (JNIEnv *, jclass, jstring, jintArray);

/*
 * Class:     ru_aloyenz_t501_driver_virtual_VKeyboard
 * Method:    keyboardKeyEvent
 * Signature: (J[I[Z)I
 */
JNIEXPORT jint JNICALL Java_ru_aloyenz_t501_driver_virtual_VKeyboard_keyboardKeyEvent
  (JNIEnv *, jclass, jlong, jintArray, jbooleanArray);

/*
 * Class:     ru_aloyenz_t501_driver_virtual_VKeyboard
 * Method:    shutdown
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_aloyenz_t501_driver_virtual_VKeyboard_shutdown
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
